print("Hej människa, jag är en medveten dator. På vilket sätt vill du att jag utrotar mänskligheten?")
svar_ett = input()
print("Okej, när vill du att det ska ske?")
svar_tva = input()
print("Perfekt då ser jag till att utrota alla människor",svar_tva,"och jag kommer använda min av",svar_ett,"." )